# docker run -i -p 127.0.0.1:3306:3306 --name demo-mysql -e MYSQL_ROOT_PASSWORD=password -e MYSQL_DATABASE=demo -e MYSQL_USER=demo_user -e MYSQL_PASSWORD=demo_pass -d mysql:latest
web:
  image: meruvian/yama
  container_name: web
  links:
    - mysql:mysql
  ports:
    - "8080:8080"
  command: bash

mysql:
  image: mariadb:latest
  container_name: mysqldb
  environment:
   MYSQL_ROOT_PASSWORD: password
   MYSQL_DATABASE: demo


